/** Keyword research — Google Ads Planner export, May 2025–Apr 2026 */

export const SEO_KEYWORDS = [
  "best digital marketing agency",
  "best ppc agency",
  "best marketing agencies",
  "best digital marketing companies",
  "best ppc companies",
  "top digital marketing companies",
  "best ecommerce marketing agency",
  "top ppc agencies",
  "top social media marketing companies",
  "best social media marketing companies",
  "best white label digital marketing agency",
  "top marketing agency",
  "best marketing agency websites",
  "best digital agencies",
  "top digital agencies",
  "best online marketing company",
  "best performance marketing agencies",
  "best online marketing",
  "top ecommerce marketing agencies",
  "best digital agency websites",
  "best white label marketing agency",
  "best website marketing companies",
  "top digital marketing agency",
  "top 10 digital marketing agencies in the world",
  "best real estate social media marketing companies",
  "best ecommerce agencies",
  "top digital marketing companies in the world",
  "best digital marketing agency websites",
  "best digital marketing agency for ecommerce",
  "digital performance marketing agency",
  "top 10 digital marketing websites",
  "best digital marketing agency in the world",
  "best local seo company",
  "top social media marketing agencies",
  "top ppc companies",
  "biggest digital marketing companies",
  "the best digital marketing agency",
  "best ppc advertising companies",
  "top performance marketing agencies",
  "top digital marketing agencies in the world",
  "top digital marketing services",
  "online marketing services near me",
  "best digital marketing website",
  "best local seo agency",
  "top ecommerce agencies",
  "best digital marketing agency for real estate",
  "best digital advertising agencies",
  "best ppc management company",
  "best seo marketing companies",
  "best digital marketing services",
  "top performance marketing companies",
  "best paid search agency",
  "best internet marketing company",
  "top 10 marketing agencies",
  "best digital marketing agency near me",
  "best content marketing agencies",
  "top 10 digital marketing companies",
  "top 10 digital marketing companies in world",
  "the best marketing agency",
  "best digital agency in the world",
  "top seo marketing companies",
  "best online advertising for real estate agents",
  "best marketing agencies for startups",
  "online digital marketing services",
  "award winning digital marketing agency",
  "best online marketing agency",
  "top social media advertising companies",
  "top 10 digital marketing agency",
  "best b2b digital marketing agencies",
  "top digital media companies",
  "best digital marketing companies in the world",
  "best white label digital marketing",
  "award winning digital agency",
  "best digital marketing firms",
  "top internet marketing companies",
  "best media marketing companies",
  "biggest social media marketing companies",
  "best ppc management",
  "top marketing agency websites",
  "internet marketing service near me",
  "best marketing agency near me",
  "top real estate digital marketing companies",
  "best ecommerce marketing companies",
  "online marketing service provider",
  "top digital marketing firm",
  "best digital marketers",
  "top digital agencies in the world",
  "best digital marketing websites in the world",
  "best digital marketing for real estate agents",
  "world best digital marketing company",
  "best digital marketing company in the world",
  "popular marketing agencies",
  "top online marketing companies",
  "top online advertising companies",
  "best web marketing companies",
] as const;

/** Highest-volume terms (5,000 avg. monthly searches) */
export const PRIMARY_SEO_KEYWORDS = [
  "best digital marketing agency",
  "best marketing agencies",
  "best digital marketing companies",
  "top digital marketing companies",
  "top marketing agency",
  "top digital marketing agency",
  "best digital marketing agency near me",
  "best digital marketing firms",
  "best digital marketers",
  "popular marketing agencies",
] as const;

export const SEO_META = {
  home: {
    title: "Best Digital Marketing Agency for Business Growth",
    description:
      "Wolfrayet Media is a top-rated digital marketing agency delivering smart, results-driven strategies that help businesses grow, boost visibility, and connect with the right audience.",
  },
  services: {
    title: "Best Digital Marketing Services | PPC, SEO & Social Media",
    description:
      "Explore top digital marketing services from a best PPC agency and best local SEO agency — paid search, content marketing, ecommerce marketing, performance marketing, and web development in India.",
  },
  about: {
    title: "Top Digital Marketing Agency | About Wolfrayet Media",
    description:
      "Wolfrayet Media was founded by Krishna Kumar, Founder & CEO. Learn about our digital marketing, web development, and IT team serving brands in India and worldwide.",
  },
  contact: {
    title: "Best Digital Marketing Agency Near Me | Contact",
    description:
      "Contact a top marketing agency for online marketing services near you. WhatsApp, AI chat, or form — best digital marketing company for SEO, PPC, and web projects.",
  },
  portfolio: {
    title: "Digital Marketing Case Studies | Top Agency Results",
    description:
      "See how our best digital marketing agency delivers SEO, PPC, branding, and ecommerce wins for clients — top performance marketing results you can measure.",
  },
  blog: {
    title: "Digital Marketing Insights | Best Agency Blog",
    description:
      "SEO, PPC, and growth strategies from one of the best content marketing agencies and top social media marketing companies — expert tips from Wolfrayet Media.",
  },
  testimonials: {
    title: "Client Reviews | Best Digital Marketing Agency",
    description:
      "Read reviews for a top digital marketing firm and popular marketing agency — real feedback from brands that chose Wolfrayet Media for online digital marketing services.",
  },
} as const;

export const SEO_SERVICE_TYPES = [
  "Digital Marketing",
  "Search Engine Optimization",
  "Pay-Per-Click Advertising",
  "Social Media Marketing",
  "Content Marketing",
  "Performance Marketing",
  "Local SEO",
  "Web Development",
  "Ecommerce Marketing",
  "IT Services",
] as const;
